_target_: hulc2.models.perceptual_encoders.vision_network.VisionNetwork
input_width: 200
input_height: 150
activation_function: ReLU #ELU
dropout_vis_fc: 0.0
l2_normalize_output: false
visual_features: 64
num_c: 3
use_sinusoid: false
spatial_softmax_temp: 1.0
