wandb_saver:
  val_loss:
    monitor: 'Validation/total_loss'
    save_top_k: 2
    mode: min
    verbose: True
  val_miou:
    monitor: 'Validation/miou'
    save_top_k: 2
    mode: max
    verbose: True
    save_last: True

model:
  cfg:
    hough_voting:
      skip_pixels: 3
      inlier_threshold: 0.8
      angle_discretization: 100
      inlier_distance: 16
      percentage_threshold: 0.4
      object_center_kernel_radius: 16

dataset: 
  _target_: hulc2.affordance.datasets.mask_label.MaskLabelLabelDataLang
  transforms: ${aff_detection.streams.transforms}
  radius:
    static: 16
    gripper: 10