wandb_saver:
  val_loss:
    monitor: 'Validation/total_loss'
    save_top_k: 2
    mode: min
    verbose: True
  val_err:
    monitor: 'Validation/px_dist_err'
    save_top_k: 2
    mode: min
    verbose: True
    save_last: True

dataset: 
  _target_: hulc2.affordance.datasets.pixel_label.PixeLabelDataLang
  transforms: ${aff_detection.streams.transforms}