_target_: lfp.models.perceptual_encoders.concat_encoders.ConcatEncoders
_recursive_: false

defaults:
 - rgb_static: resnet_aff
 - rgb_gripper: resnet_aff
 - depth_static: none
 - depth_gripper: none
 - proprio: none
 - tactile: none
