_target_: hulc2.models.perceptual_encoders.concat_encoders.ConcatEncoders
_recursive_: false

defaults:
 - rgb_static: default
 - rgb_gripper: default
 - depth_static: default
 - depth_gripper: default
 - proprio: none
 - tactile: none
