_target_: pytorch_lightning.callbacks.ModelCheckpoint
save_top_k: -1
verbose: True
monitor: val_act/action_loss_pp
mode: min
dirpath: saved_models
filename: '{epoch}' #put back in when PL fixes this _{val/accuracy:.4f}'
