_target_: hulc2.models.decoders.gaussian_policy_network.GaussianPolicyNetwork
n_mixtures: 10
hidden_size: 2048
out_features: ${datamodule.action_space}
policy_rnn_dropout_p: 0.0
perceptual_features: ??
latent_goal_features: ${model.visual_goal.latent_goal_features}
plan_features: ???
log_scale_min: -7.0
log_scale_max: 7.0
num_layers: 2
rnn_model: rnn_decoder
perceptual_emb_slice: [64, 128]
gripper_control: true
