_target_: hulc2.models.decoders.logistic_discrete_gripper_transformer.LogisticDiscreteGripperTransformerPolicyNetwork
n_mixtures: 10
hidden_size: 2048
out_features: ${datamodule.action_space}
log_scale_min: -7.0
act_max_bound: ${datamodule.action_max}
act_min_bound: ${datamodule.action_min}
dataset_dir: ${datamodule.root_data_dir}
policy_dropout_p: 0.1
load_action_bounds: false
num_classes: 10
latent_goal_features: ${model.visual_goal.latent_goal_features}
plan_features: ???
perceptual_features: ???
gripper_alpha: 1.0
num_heads: 8
num_layers: 2
max_position_embeddings: ${datamodule.datasets.lang_dataset.max_window_size}
