_target_: hulc2.models.encoders.goal_encoders.LanguageGoalEncoder
in_features: 384
hidden_size: 2048
latent_goal_features: 32
l2_normalize_goal_embeddings: False
activation_function: ReLU #ELU
word_dropout_p: 0.0
