_target_: calvin_env.scene.play_table_scene.PlayTableScene
_recursive_: false
data_path: ${paths.vr_data}
global_scaling: 0.8
euler_obs: True
robot_base_position: [0.3, 0.15, 0.45]
robot_base_orientation: [0, 0, 1.5707963]
robot_initial_joint_positions: [-0.3457686708019129, -0.15454379621111053, -0.6607497652179231, -2.431721569843283, -0.12811896258574057, 2.3050911768605884, -0.128854091294185]
surfaces: []

objects:
  fixed_objects:
    table:
      file: table/hightable.urdf
      initial_pos: [0.3, 0.7, 0.02]
      initial_orn: [0, 0, 0]
      fixed: true
    bin:
      file: ais_objects/bin_10_30_50/bin_10_30_50.urdf
      initial_pos: [0.7, 0.75, 0.6]
      initial_orn: [1.57, 0, 0]
      fixed: true
  movable_objects:
    bowl:
      file: 024_bowl/google_16k/textured.urdf
      initial_pos: [0.18, 0.58, 0.6230520401985216]
      initial_orn: [0, 0, 0]
      fixed: false
