defaults:
  - datasets: vision_lang
  - transforms: real_world_r3m
  - proprioception_dims: robot_no_joints #robot_full
  - observation_space: lang_rgb_static_gripper_rel_gripper_act
_target_: hulc2.datasets.play_data_module.PlayDataModule
_recursive_: false
root_data_dir: "play_data"
action_space: 7
action_max: [1., 1., 1., 1., 1., 1., 1.,]
action_min: [-1., -1., -1., -1., -1., -1., -1]
shuffle_val: false
